### ISSUE TITLE
Support Dart SDK > 2.0.0

### ISSUE THREAD

**Issue by Sub6Resources** [brianegan/open_iconic_flutter#1]
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

I'm currently getting this error when building chewie (which I'm sure you know depends on this library)

       Because chewie >=0.4.0 depends on open_iconic_flutter >=0.2.0 which requires SDK version <2.0.0, chewie >=0.4.0 is forbidden.
        So, because membership_coach depends on chewie ^0.6.1, version solving failed.

**Comment by Sub6Resources** [comment]
Chewie won't work for most people now because of this issue.

**Comment by marianoarga** [comment]
+1

**Comment by brianegan** [comment]
Thanks all! I've now updated this package to `0.3.0` and Chewie to `0.7.0`.  Tested with latest Flutter beta that uses Dart 2.0-edge.
